import Head from 'next/head';

const header = function header() {
  return (
    <Head>
      <title>toy project oAuth2.0</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default header;
